dbt_basics:
  target: dev # default target
  outputs:
    dev: 
      type: snowflake
      account: xnfepvm-lo69498
      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: PC_DBT_ROLE
      database: PC_DBT_DB
      warehouse: PC_DBT_WH
      schema: "DBT_MPARIVARTON" # Dynamically creates schemas for the users
      threads: 1
      client_session_keep_alive: False